### ISSUE TITLE
SSH KEY STUFF

### ISSUE THREAD

**Issue by crazybytes** [kbinani/mcview#2]
For loading from command line with git clone --recursive ...

the download fails because of the ssh stuff.
You know how to fix that?
I've made a key, followed guidelines, but it does not work....
Only the main source is downloaded, the rest gives:

E:\MODDING\EDIT>git clone --recursive https://github.com/kbinani/mcview.git
Cloning into 'mcview'...
remote: Enumerating objects: 228, done.
remote: Counting objects: 100% (228/228), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 1142 (delta 149), reused 160 (delta 90), pack-reused 914
Receiving objects: 100% (1142/1142), 13.02 MiB | 5.07 MiB/s, done.
Resolving deltas: 100% (756/756), done.
Submodule 'ext/JUCE' (git@github.com:kbinani/JUCE.git) registered for path 'ext/JUCE'
Submodule 'ext/colormap-shaders' (git@github.com:kbinani/colormap-shaders.git) registered for path 'ext/colormap-shaders'
Submodule 'ext/libminecraft-file' (git@github.com:kbinani/libminecraft-file.git) registered for path 'ext/libminecraft-file'
Cloning into 'E:/MODDING/EDIT/mcview/ext/JUCE'...
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kbinani/JUCE.git' into submodule path 'E:/MODDING/EDIT/mcview/ext/JUCE' failed
Failed to clone 'ext/JUCE'. Retry scheduled
Cloning into 'E:/MODDING/EDIT/mcview/ext/colormap-shaders'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kbinani/colormap-shaders.git' into submodule path 'E:/MODDING/EDIT/mcview/ext/colormap-shaders' failed
Failed to clone 'ext/colormap-shaders'. Retry scheduled
Cloning into 'E:/MODDING/EDIT/mcview/ext/libminecraft-file'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kbinani/libminecraft-file.git' into submodule path 'E:/MODDING/EDIT/mcview/ext/libminecraft-file' failed
Failed to clone 'ext/libminecraft-file'. Retry scheduled
Cloning into 'E:/MODDING/EDIT/mcview/ext/JUCE'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kbinani/JUCE.git' into submodule path 'E:/MODDING/EDIT/mcview/ext/JUCE' failed
Failed to clone 'ext/JUCE' a second time, aborting

**Comment by crazybytes** [comment]
Maybe you can fix it, so i can get the thing going?
(Of course i am doing something wrong, i know....)

**Comment by kbinani** [comment]
Fixed by #3

@crazybytes Thank you notifying about this issue.

```
git submodule sync
git submodule update --init --recursive
```
Could you try these commands?

**Comment by crazybytes** [comment]
Ok. I try them.
After the git clone --recursive https://github.com/kbinani/mcview.git ??

The problem is i made a rsa key, that is working fine for cuberite c++
minecraft server.
But when using git from command shell it gives this errors on the sub
modules:



D:\PACMAN\test>git clone --recursive https://github.com/kbinani/mcview.git
Cloning into 'mcview'...
remote: Enumerating objects: 259, done.
remote: Counting objects: 100% (259/259), done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 1173 (delta 161), reused 180 (delta 95), pack-reused 914
Receiving objects: 100% (1173/1173), 16.95 MiB | 5.36 MiB/s, done.
Resolving deltas: 100% (768/768), done.
Submodule 'ext/JUCE' (https://github.com/kbinani/JUCE.git) registered for
path 'ext/JUCE'
Submodule 'ext/colormap-shaders' (
https://github.com/kbinani/colormap-shaders.git) registered for path
'ext/colormap-shaders'
Submodule 'ext/libminecraft-file' (
https://github.com/kbinani/libminecraft-file.git) registered for path
'ext/libminecraft-file'
Cloning into 'D:/PACMAN/test/mcview/ext/JUCE'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 186190 (delta 10), reused 4 (delta 4), pack-reused 186176
Receiving objects: 100% (186190/186190), 211.52 MiB | 5.98 MiB/s, done.
Resolving deltas: 100% (146520/146520), done.
Cloning into 'D:/PACMAN/test/mcview/ext/colormap-shaders'...
remote: Enumerating objects: 1073, done.
remote: Total 1073 (delta 0), reused 0 (delta 0), pack-reused 1073
Receiving objects: 100% (1073/1073), 435.84 KiB | 842.00 KiB/s, done.
Resolving deltas: 100% (492/492), done.
Cloning into 'D:/PACMAN/test/mcview/ext/libminecraft-file'...
remote: Enumerating objects: 291, done.
remote: Counting objects: 100% (291/291), done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 291 (delta 128), reused 266 (delta 103), pack-reused 0
Receiving objects: 100% (291/291), 1.23 MiB | 2.27 MiB/s, done.
Resolving deltas: 100% (128/128), done.
Submodule path 'ext/JUCE': checked out
'a7ae5402d0b8afec936bfa99ac32bbe2bf952d95'
Submodule path 'ext/colormap-shaders': checked out
'7ddaa34978c4729cfe6eddaf7bf68bb4831760bb'
Submodule path 'ext/libminecraft-file': checked out
'bbbb5c95e46d7797a4b27f4f9e0e42eb105a8a5a'
Submodule 'example/ext/colormap-shaders'
(git@github.com:kbinani/colormap-shaders.git)
registered for path 'ext/libminecraft-file/example/ext/colormap-shaders'
Submodule 'example/ext/hwm.task' (git@github.com:hotwatermorning/hwm.task.git)
registered for path 'ext/libminecraft-file/example/ext/hwm.task'
Submodule 'example/ext/svpng' (git@github.com:miloyip/svpng.git) registered
for path 'ext/libminecraft-file/example/ext/svpng'
Submodule 'test/ext/doctest' (git@github.com:onqtam/doctest.git) registered
for path 'ext/libminecraft-file/test/ext/doctest'
Cloning into
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/colormap-shaders'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kbinani/colormap-shaders.git' into
submodule path
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/colormap-shaders'
failed
Failed to clone 'example/ext/colormap-shaders'. Retry scheduled
Cloning into
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/hwm.task'...
Warning: Permanently added the RSA host key for IP address '140.82.114.3'
to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hotwatermorning/hwm.task.git' into
submodule path
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/hwm.task' failed
Failed to clone 'example/ext/hwm.task'. Retry scheduled
Cloning into
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/svpng'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:miloyip/svpng.git' into submodule path
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/svpng' failed
Failed to clone 'example/ext/svpng'. Retry scheduled
Cloning into
'D:/PACMAN/test/mcview/ext/libminecraft-file/test/ext/doctest'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:onqtam/doctest.git' into submodule path
'D:/PACMAN/test/mcview/ext/libminecraft-file/test/ext/doctest' failed
Failed to clone 'test/ext/doctest'. Retry scheduled
Cloning into
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/colormap-shaders'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kbinani/colormap-shaders.git' into
submodule path
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/colormap-shaders'
failed
Failed to clone 'example/ext/colormap-shaders' a second time, aborting
Failed to recurse into submodule path 'ext/libminecraft-file'

D:\PACMAN\test>

When using the commands you gave me same...:

D:\PACMAN\test\mcview>git submodule sync
Synchronizing submodule url for 'ext/JUCE'
Synchronizing submodule url for 'ext/colormap-shaders'
Synchronizing submodule url for 'ext/libminecraft-file'

D:\PACMAN\test\mcview>git submodule update --init --recursive
Cloning into
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/colormap-shaders'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3'
to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kbinani/colormap-shaders.git' into
submodule path
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/colormap-shaders'
failed
Failed to clone 'example/ext/colormap-shaders'. Retry scheduled
Cloning into
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/hwm.task'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hotwatermorning/hwm.task.git' into
submodule path
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/hwm.task' failed
Failed to clone 'example/ext/hwm.task'. Retry scheduled
Cloning into
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/svpng'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:miloyip/svpng.git' into submodule path
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/svpng' failed
Failed to clone 'example/ext/svpng'. Retry scheduled
Cloning into
'D:/PACMAN/test/mcview/ext/libminecraft-file/test/ext/doctest'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:onqtam/doctest.git' into submodule path
'D:/PACMAN/test/mcview/ext/libminecraft-file/test/ext/doctest' failed
Failed to clone 'test/ext/doctest'. Retry scheduled
Cloning into
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/colormap-shaders'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kbinani/colormap-shaders.git' into
submodule path
'D:/PACMAN/test/mcview/ext/libminecraft-file/example/ext/colormap-shaders'
failed
Failed to clone 'example/ext/colormap-shaders' a second time, aborting
Failed to recurse into submodule path 'ext/libminecraft-file'

D:\PACMAN\test\mcview>

Op za 17 aug. 2019 om 16:24 schreef kbinani <notifications@github.com>:

**Comment by crazybytes** [comment]
Ok. Now its working under linux (Ubuntu).
Will test if git under windows it also works.
Its something with the ssh keys.
But i don't understand it fully.
But its cloning now...
Thanks for so far.

Op ma 19 aug. 2019 om 12:25 schreef Gerard Wensink <gerardwensink@gmail.com

**Comment by crazybytes** [comment]
Yes. Under windows it also clones recursive.
Going back to step 2.
compiling....

Op ma 19 aug. 2019 om 13:04 schreef Gerard Wensink <gerardwensink@gmail.com
